module.exports = {
  ROLES: {
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    ACCOUNTANT: 'accountant',
    USER: 'user',
    DISTRIBUTOR: 'distributor',
    SALESMAN: 'salesman',
    FINANCE_MANAGER: 'finance_manager',
  },
  NOTIFICATION_TYPES: {
    // User & Account
    NEW_USER_ADDED: 'new_user_added',
    USER_PROFILE_UPDATED: 'user_profile_updated',
    PASSWORD_CHANGED: 'password_changed',
    ACCOUNT_ACTIVATED: 'account_activated',
    ACCOUNT_DEACTIVATED: 'account_deactivated',
    LOGIN_ALERT: 'login_alert',
    // Target & Performance
    TARGET_CREATED: 'target_created',
    TARGET_PENDING: 'target_pending',
    TARGET_ACHIEVED: 'target_achieved',
    TARGET_EXCEEDED: 'target_exceeded',
    TARGET_BEHIND: 'target_behind',
    TARGET_DEADLINE_WARNING: 'target_deadline_warning',
    TARGET_EXPIRED: 'target_expired',
    // Commission & Payout
    COMMISSION_CREATED: 'commission_created',
    COMMISSION_APPROVED: 'commission_approved',
    COMMISSION_PAID: 'commission_paid',
    COMMISSION_REJECTED: 'commission_rejected',
    HIGH_COMMISSION_ALERT: 'high_commission_alert',
    PAYOUT_GENERATED: 'payout_generated',
    PAYOUT_PROCESSING: 'payout_processing',
    PAYOUT_COMPLETED: 'payout_completed',
    PAYOUT_FAILED: 'payout_failed',
    // Tenant & Subscription
    NEW_TENANT_CREATED: 'new_tenant_created',
    SUBSCRIPTION_ACTIVATED: 'subscription_activated',
    SUBSCRIPTION_RENEWAL_DUE: 'subscription_renewal_due',
    SUBSCRIPTION_EXPIRED: 'subscription_expired',
    SUBSCRIPTION_UPGRADED: 'subscription_upgraded',
    SUBSCRIPTION_DOWNGRADED: 'subscription_downgraded',
    PAYMENT_RECEIVED: 'payment_received',
    PAYMENT_FAILED: 'payment_failed',
    // Referral
    REFERRAL_CODE_USED: 'referral_code_used',
    REFERRAL_REWARD_EARNED: 'referral_reward_earned',
    REFERRAL_REWARD_APPROVED: 'referral_reward_approved',
    REFERRAL_REWARD_PAID: 'referral_reward_paid',
    // Support
    NEW_SUPPORT_TICKET: 'new_support_ticket',
    TICKET_ASSIGNED: 'ticket_assigned',
    TICKET_STATUS_CHANGED: 'ticket_status_changed',
    NEW_TICKET_MESSAGE: 'new_ticket_message',
    TICKET_RESOLVED: 'ticket_resolved',
    TICKET_CLOSED: 'ticket_closed',
    // System & Admin
    SYSTEM_MAINTENANCE: 'system_maintenance',
    SYSTEM_UPDATE: 'system_update',
    CONFIGURATION_CHANGED: 'configuration_changed',
    BACKUP_COMPLETED: 'backup_completed',
    ERROR_ALERT: 'error_alert',
    // Distributor/Salesman Specific
    NEW_LEAD_ASSIGNED: 'new_lead_assigned',
    LEAD_STATUS_CHANGED: 'lead_status_changed',
    LEAD_CONVERTED: 'lead_converted',
    PERFORMANCE_MILESTONE: 'performance_milestone',
    TERRITORY_UPDATED: 'territory_updated',
  },
  NOTIFICATION_PRIORITY: {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
  },
  VOUCHER_TYPES: {
    SALES: 'sales',
    PURCHASE: 'purchase',
    PAYMENT: 'payment',
    RECEIPT: 'receipt',
    JOURNAL: 'journal',
    CONTRA: 'contra',
  },
  VOUCHER_STATUS: {
    DRAFT: 'draft',
    POSTED: 'posted',
    CANCELLED: 'cancelled',
  },
  COMMISSION_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    PAID: 'paid',
    CANCELLED: 'cancelled',
  },
  PAYOUT_STATUS: {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
  },
  LEAD_STATUS: {
    NEW: 'new',
    CONTACTED: 'contacted',
    QUALIFIED: 'qualified',
    CONVERTED: 'converted',
    LOST: 'lost',
  },
  GSTR_RETURN_TYPES: {
    GSTR1: 'GSTR1',
    GSTR3B: 'GSTR3B',
    GSTR9: 'GSTR9',
  },
  E_INVOICE_STATUS: {
    PENDING: 'pending',
    GENERATED: 'generated',
    CANCELLED: 'cancelled',
    FAILED: 'failed',
  },
};
