/**
 * Notification Type Configuration
 * Maps notification types to their display properties, icons, colors, and behavior
 */

export const NOTIFICATION_TYPES = {
  // User & Account
  NEW_USER_ADDED: 'new_user_added',
  USER_PROFILE_UPDATED: 'user_profile_updated',
  PASSWORD_CHANGED: 'password_changed',
  ACCOUNT_ACTIVATED: 'account_activated',
  ACCOUNT_DEACTIVATED: 'account_deactivated',
  LOGIN_ALERT: 'login_alert',
  // Target & Performance
  TARGET_CREATED: 'target_created',
  TARGET_PENDING: 'target_pending',
  TARGET_ACHIEVED: 'target_achieved',
  TARGET_EXCEEDED: 'target_exceeded',
  TARGET_BEHIND: 'target_behind',
  TARGET_DEADLINE_WARNING: 'target_deadline_warning',
  TARGET_EXPIRED: 'target_expired',
  // Commission & Payout
  COMMISSION_CREATED: 'commission_created',
  COMMISSION_APPROVED: 'commission_approved',
  COMMISSION_PAID: 'commission_paid',
  COMMISSION_REJECTED: 'commission_rejected',
  HIGH_COMMISSION_ALERT: 'high_commission_alert',
  PAYOUT_GENERATED: 'payout_generated',
  PAYOUT_PROCESSING: 'payout_processing',
  PAYOUT_COMPLETED: 'payout_completed',
  PAYOUT_FAILED: 'payout_failed',
  // Tenant & Subscription
  NEW_TENANT_CREATED: 'new_tenant_created',
  SUBSCRIPTION_ACTIVATED: 'subscription_activated',
  SUBSCRIPTION_RENEWAL_DUE: 'subscription_renewal_due',
  SUBSCRIPTION_EXPIRED: 'subscription_expired',
  SUBSCRIPTION_UPGRADED: 'subscription_upgraded',
  SUBSCRIPTION_DOWNGRADED: 'subscription_downgraded',
  PAYMENT_RECEIVED: 'payment_received',
  PAYMENT_FAILED: 'payment_failed',
  // Referral
  REFERRAL_CODE_USED: 'referral_code_used',
  REFERRAL_REWARD_EARNED: 'referral_reward_earned',
  REFERRAL_REWARD_APPROVED: 'referral_reward_approved',
  REFERRAL_REWARD_PAID: 'referral_reward_paid',
  // Support
  NEW_SUPPORT_TICKET: 'new_support_ticket',
  TICKET_ASSIGNED: 'ticket_assigned',
  TICKET_STATUS_CHANGED: 'ticket_status_changed',
  NEW_TICKET_MESSAGE: 'new_ticket_message',
  TICKET_RESOLVED: 'ticket_resolved',
  TICKET_CLOSED: 'ticket_closed',
  // System & Admin
  SYSTEM_MAINTENANCE: 'system_maintenance',
  SYSTEM_UPDATE: 'system_update',
  CONFIGURATION_CHANGED: 'configuration_changed',
  BACKUP_COMPLETED: 'backup_completed',
  ERROR_ALERT: 'error_alert',
  // Distributor/Salesman Specific
  NEW_LEAD_ASSIGNED: 'new_lead_assigned',
  LEAD_STATUS_CHANGED: 'lead_status_changed',
  LEAD_CONVERTED: 'lead_converted',
  PERFORMANCE_MILESTONE: 'performance_milestone',
  TERRITORY_UPDATED: 'territory_updated',
};

export const NOTIFICATION_PRIORITY = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
};

/**
 * Notification category configurations
 * Defines visual styling, icons, and default duration for each notification type
 */
export const NOTIFICATION_CONFIG = {
  // Success types (green)
  [NOTIFICATION_TYPES.TARGET_ACHIEVED]: {
    category: 'success',
    icon: '🎉',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.TARGET_EXCEEDED]: {
    category: 'success',
    icon: '🚀',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.COMMISSION_APPROVED]: {
    category: 'success',
    icon: '✅',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.COMMISSION_PAID]: {
    category: 'success',
    icon: '💰',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.PAYOUT_COMPLETED]: {
    category: 'success',
    icon: '✅',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.ACCOUNT_ACTIVATED]: {
    category: 'success',
    icon: '✅',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.SUBSCRIPTION_ACTIVATED]: {
    category: 'success',
    icon: '✨',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.SUBSCRIPTION_UPGRADED]: {
    category: 'success',
    icon: '⬆️',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.PAYMENT_RECEIVED]: {
    category: 'success',
    icon: '💳',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.REFERRAL_REWARD_PAID]: {
    category: 'success',
    icon: '🎁',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.TICKET_RESOLVED]: {
    category: 'success',
    icon: '✅',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.BACKUP_COMPLETED]: {
    category: 'success',
    icon: '💾',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.LEAD_CONVERTED]: {
    category: 'success',
    icon: '🎯',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.PERFORMANCE_MILESTONE]: {
    category: 'success',
    icon: '🏆',
    color: '#10b981',
    bgColor: '#d1fae5',
    borderColor: '#10b981',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },

  // Error types (red)
  [NOTIFICATION_TYPES.COMMISSION_REJECTED]: {
    category: 'error',
    icon: '❌',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.PAYOUT_FAILED]: {
    category: 'error',
    icon: '⚠️',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 6000,
    priority: NOTIFICATION_PRIORITY.CRITICAL,
  },
  [NOTIFICATION_TYPES.ACCOUNT_DEACTIVATED]: {
    category: 'error',
    icon: '🔒',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.SUBSCRIPTION_EXPIRED]: {
    category: 'error',
    icon: '⏰',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 6000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.SUBSCRIPTION_DOWNGRADED]: {
    category: 'error',
    icon: '⬇️',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: {
    category: 'error',
    icon: '💳',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 6000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.TARGET_EXPIRED]: {
    category: 'error',
    icon: '⏰',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.ERROR_ALERT]: {
    category: 'error',
    icon: '🚨',
    color: '#ef4444',
    bgColor: '#fee2e2',
    borderColor: '#ef4444',
    duration: 6000,
    priority: NOTIFICATION_PRIORITY.CRITICAL,
  },

  // Warning types (yellow/orange)
  [NOTIFICATION_TYPES.TARGET_PENDING]: {
    category: 'warning',
    icon: '⏳',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.TARGET_BEHIND]: {
    category: 'warning',
    icon: '⚠️',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.TARGET_DEADLINE_WARNING]: {
    category: 'warning',
    icon: '⏰',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.SUBSCRIPTION_RENEWAL_DUE]: {
    category: 'warning',
    icon: '⏳',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 6000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.HIGH_COMMISSION_ALERT]: {
    category: 'warning',
    icon: '💰',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.LOGIN_ALERT]: {
    category: 'warning',
    icon: '🔐',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    borderColor: '#f59e0b',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },

  // Info types (blue)
  [NOTIFICATION_TYPES.NEW_USER_ADDED]: {
    category: 'info',
    icon: '👤',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.USER_PROFILE_UPDATED]: {
    category: 'info',
    icon: '📝',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.PASSWORD_CHANGED]: {
    category: 'info',
    icon: '🔑',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.TARGET_CREATED]: {
    category: 'info',
    icon: '🎯',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.COMMISSION_CREATED]: {
    category: 'info',
    icon: '💵',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.PAYOUT_GENERATED]: {
    category: 'info',
    icon: '📄',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.PAYOUT_PROCESSING]: {
    category: 'info',
    icon: '⏳',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.NEW_TENANT_CREATED]: {
    category: 'info',
    icon: '🏢',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.REFERRAL_CODE_USED]: {
    category: 'info',
    icon: '🎫',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.REFERRAL_REWARD_EARNED]: {
    category: 'info',
    icon: '🎁',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.REFERRAL_REWARD_APPROVED]: {
    category: 'info',
    icon: '✅',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.NEW_SUPPORT_TICKET]: {
    category: 'info',
    icon: '🎫',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.TICKET_ASSIGNED]: {
    category: 'info',
    icon: '👤',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.TICKET_STATUS_CHANGED]: {
    category: 'info',
    icon: '🔄',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.NEW_TICKET_MESSAGE]: {
    category: 'info',
    icon: '💬',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.TICKET_CLOSED]: {
    category: 'info',
    icon: '🔒',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.SYSTEM_MAINTENANCE]: {
    category: 'info',
    icon: '🔧',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 8000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.SYSTEM_UPDATE]: {
    category: 'info',
    icon: '🆕',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 5000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  },
  [NOTIFICATION_TYPES.CONFIGURATION_CHANGED]: {
    category: 'info',
    icon: '⚙️',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.NEW_LEAD_ASSIGNED]: {
    category: 'info',
    icon: '📋',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.HIGH,
  },
  [NOTIFICATION_TYPES.LEAD_STATUS_CHANGED]: {
    category: 'info',
    icon: '🔄',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
  [NOTIFICATION_TYPES.TERRITORY_UPDATED]: {
    category: 'info',
    icon: '🗺️',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 3000,
    priority: NOTIFICATION_PRIORITY.LOW,
  },
};

/**
 * Get notification configuration by type
 * @param {string} type - Notification type
 * @returns {Object} Configuration object
 */
export function getNotificationConfig(type) {
  return NOTIFICATION_CONFIG[type] || {
    category: 'info',
    icon: 'ℹ️',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    borderColor: '#3b82f6',
    duration: 4000,
    priority: NOTIFICATION_PRIORITY.MEDIUM,
  };
}

/**
 * Get all notification types by category
 * @param {string} category - Category (success, error, warning, info)
 * @returns {Array} Array of notification types
 */
export function getNotificationsByCategory(category) {
  return Object.entries(NOTIFICATION_CONFIG)
    .filter(([_, config]) => config.category === category)
    .map(([type]) => type);
}
